<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>xy.Cfg</RootNamespace>
    <PackageOutputPath>..\..\package</PackageOutputPath>
    <Title>Configuration manager</Title>
    <Version>1.0.3</Version>
    <Authors>dooacontrol</Authors>
    <Company>dooacontrol</Company>
    <Description>A simple library for application configuration management</Description>
    <PackageProjectUrl>https://github.com/doobcontrol/xyCfg</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
